textBro/main/urls.py
from django.urls import path

from . import views

app_name = 'textBro'


urlpatterns = [
    path('', views.index, name='index'),
    path('<str:link>/<str:password>/', views.editText, name="editText"),
    path('<str:link>/', views.editTextAskPassword, name="editTextAskPassword"),
    path('save/<str:link>/<str:password>/', views.saveText, name="saveText"),
    path('saveTab/<str:link>/<str:password>/<str:tab>', views.saveTextNewTab, name="saveTextTab"),
    path('newtab/<str:link>/<str:password>/', views.newTab, name="newTab"),
    path('verify', views.verify, name="verify"),
    path('openTab/<str:link>/<str:password>/<str:tab>', views.openTab, name="openTab"),
    path('saveTabInside/<str:link>/<str:password>/<str:tab>', views.saveTextTabInside, name="saveTabInside"),
]

textBro/textBro/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('admin/page', admin.site.urls),
]

textBro/main/models.py
from django.db import models


class texts(models.Model):
    text_link = models.CharField(max_length=20, unique=True)
    text_password = models.CharField(max_length=100)
    text = models.TextField(default="", blank=True)
    text1 = models.TextField(default="", blank=True)
    text2 = models.TextField(default="", blank=True)
    text3 = models.TextField(default="", blank=True)
    text4 = models.TextField(default="", blank=True)
    text5 = models.TextField(default="", blank=True)
    text6 = models.TextField(default="", blank=True)
    text7 = models.TextField(default="", blank=True)
    text8 = models.TextField(default="", blank=True)
    text9 = models.TextField(default="", blank=True)

textBro/main/forms.py
from django import forms
from . import models


class textsForm(forms.ModelForm):
    class Meta:
        model = models.texts
        fields = ['text_link', 'text_password']

textBro/main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import textsForm
from .models import texts
import hashlib


def index(request):
    form = textsForm()
    if request.method == 'POST':
        form = textsForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.text_password = hashlib.sha256(instance.text_password.encode('utf-8')).hexdigest()
            instance.save()
            next = request.POST.get('next', '/')
            return HttpResponseRedirect(next)
    else:
        form = textsForm()
    return render(request, 'homepage.html', {'form': form})


def editText(request, link, password):
    instance = texts.objects.get(text_link=link, text_password=password)
    context = {'link': instance.text_link, 'text': instance.text, 'password': instance.text_password, 'text1': instance.text1, 'text2': instance.text2, 'text3': instance.text3, 'text4': instance.text4, 'text5': instance.text5, 'text6': instance.text6, 'text7': instance.text7, 'text8': instance.text8, 'text9': instance.text9}
    return render(request, 'editText.html', context)


def newTab(request, link, password):
    sendText = ""
    sendTab = ""
    instance = texts.objects.get(text_link=link, text_password=password)
    if instance.text1 == "":
        sendText = instance.text1
        sendTab = "text1"
    elif instance.text2 == "":
        sendText = instance.text2
        sendTab = "text2"
    elif instance.text3 == "":
        sendText = instance.text3
        sendTab = "text3"
    elif instance.text4 == "":
        sendText = instance.text4
        sendTab = "text4"
    elif instance.text5 == "":
        sendText = instance.text5
        sendTab = "text5"
    elif instance.text6 == "":
        sendText = instance.text6
        sendTab = "text6"
    elif instance.text7 == "":
        sendText = instance.text7
        sendTab = "text7"
    elif instance.text8 == "":
        sendText = instance.text8
        sendTab = "text8"
    elif instance.text9 == "":
        sendText = instance.text9
        sendTab = "text9"
    else:
        return HttpResponse("All tab full")

    context = {'link': instance.text_link, 'text': sendText, 'password': instance.text_password, 'tab': sendTab}
    return render(request, 'newTab.html', context)


def editTextAskPassword(request, link):
    context = {'link': link}
    enterPassword = ""
    if request.method == "POST":
        enterPassword = request.POST['enter-text-password']
    if enterPassword != "":
        check_password = hashlib.sha256(enterPassword.encode('utf-8')).hexdigest()
        return redirect('/' + link + '/' + check_password)
    return render(request, 'password.html', context)


def saveText(request, link, password):
    instance = texts.objects.get(text_link=link)
    if request.method == "POST":
        textEditBox = request.POST['edit-box']
    instance.text = textEditBox
    instance.save()
    return redirect('/' + link + '/' + password)


def saveTextNewTab(request, link, password, tab):
    instance = texts.objects.get(text_link=link)
    print(tab)

    if request.method == "POST":
        textEditBox = request.POST['edit-box-tab']
    if tab == "text1":
        instance.text1 = textEditBox
    elif tab == "text2":
        instance.text2 = textEditBox
    elif tab == "text3":
        instance.text3 = textEditBox
    elif tab == "text4":
        instance.text4 = textEditBox
    elif tab == "text5":
        instance.text5 = textEditBox
    elif tab == "text6":
        instance.text6 = textEditBox
    elif tab == "text7":
        instance.text7 = textEditBox
    elif tab == "text8":
        instance.text8 = textEditBox
    elif tab == "text9":
        instance.text9 = textEditBox

    instance.save()
    return redirect('/'+'openTab/' + link + '/' + password + '/' + tab)


def verify(request):
    instance = None
    if request.method == "POST":
        link_input = request.POST['text-link']
        password_input = request.POST['text-password']
        check_password = hashlib.sha256(password_input.encode('utf-8')).hexdigest()
        try:
            instance = texts.objects.get(text_link=link_input, text_password=check_password)
        except Exception as e:
            print(e)
        if instance is not None:
            return redirect('/' + link_input+'/'+check_password)
        else:
            return redirect('/')
    return redirect('/')


def openTab(request, link, password, tab):
    instance = texts.objects.get(text_link=link, text_password=password)
    if tab == "text1":
        sendText = instance.text1
    elif tab == "text2":
        sendText = instance.text2
    elif tab == "text3":
        sendText = instance.text3
    elif tab == "text4":
        sendText = instance.text4
    elif tab == "text5":
        sendText = instance.text5
    elif tab == "text6":
        sendText = instance.text6
    elif tab == "text7":
        sendText = instance.text7
    elif tab == "text8":
        sendText = instance.text8
    elif tab == "text9":
        sendText = instance.text9
    else:
        return HttpResponse("Tab not found")

    context = {'link': instance.text_link, 'text': sendText, 'password': instance.text_password, 'tab': tab}
    return render(request, 'newTab.html', context)


def saveTextTabInside(request, link, password, tab):
    instance = texts.objects.get(text_link=link)
    print(tab)

    if request.method == "POST":
        textEditBox = request.POST['edit-box-tab']
    if tab == "text1":
        instance.text1 = textEditBox
    elif tab == "text2":
        instance.text2 = textEditBox
    elif tab == "text3":
        instance.text3 = textEditBox
    elif tab == "text4":
        instance.text4 = textEditBox
    elif tab == "text5":
        instance.text5 = textEditBox
    elif tab == "text6":
        instance.text6 = textEditBox
    elif tab == "text7":
        instance.text7 = textEditBox
    elif tab == "text8":
        instance.text8 = textEditBox
    elif tab == "text9":
        instance.text9 = textEditBox

    instance.save()
    return redirect('/'+'openTab/' + link + '/' + password + '/' + tab)

textBro/main/templates/editText.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<form method="POST" action="{% url 'textBro:saveText' link password %}">
		{% csrf_token %}
{{ link }}<br>
<textarea name="edit-box" rows="4" cols="50" maxlength="200">
{{ text }}
</textarea>
    <button type="submit">Save</button>
</form>

<a href="{% url 'textBro:newTab' link password %}">New tab</a>
<br>
{% if text1 != ""  %}
<a href="{% url 'textBro:openTab' link password 'text1' %}">Tab 1 </a> <br>
{% endif %}
{% if text2 != ""  %}
<a href="{% url 'textBro:openTab' link password 'text2' %}">Tab 2 </a> <br>
{% endif %}
{% if text3 != ""  %}
<a href="{% url 'textBro:openTab' link password 'text3' %}">Tab 3 </a> <br>
{% endif %}
{% if text4 != ""  %}
<a href="{% url 'textBro:openTab' link password 'text4' %}">Tab 4 </a> <br>
{% endif %}
{% if text5 != ""  %}
<a href="{% url 'textBro:openTab' link password 'text5' %}">Tab 5 </a> <br>
{% endif %}
{% if text6 != ""  %}
<a href="{% url 'textBro:openTab' link password 'text6' %}">Tab 6 </a> <br>
{% endif %}
{% if text7 != ""  %}
<a href="{% url 'textBro:openTab' link password 'text7' %}">Tab 7 </a> <br>
{% endif %}
{% if text8 != ""  %}
<a href="{% url 'textBro:openTab' link password 'text8' %}">Tab 8 </a> <br>
{% endif %}
{% if text9 != ""  %}
<a href="{% url 'textBro:openTab' link password 'text9' %}">Tab 9 </a> <br>
{% endif %}

</body>
</html>

textBro/main/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
{% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
            </div>
        {% endfor %}
<form method="post">
    {% csrf_token %}
    {{ form.text_link }}
    {{ form.text_password }}
    <input type="submit" value="Submit">
</form>
<br>
<br>
<br>
<br>
<br>
<form method="post" action="{% url 'textBro:verify' %}">
    {% csrf_token %}
    <input type="text" name="text-link">
    <input type="text" name="text-password">
    <input type="submit" value="Submit">
</form>
</body>
</html>

textBro/main/templates/newTab.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="POST" action="{% url 'textBro:saveTextTab' link password tab %}">
		{% csrf_token %}
{{ link }}<br>
<textarea name="edit-box-tab" rows="4" cols="50" maxlength="200">
{{ text }}
</textarea>
    <button type="submit">Save</button>
</form>

</body>
</html>

textBro/main/templates/openTab.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action="{% url 'textBro:saveTabInside' link password tab %}">
		{% csrf_token %}
{{ link }}<br>
<textarea name="edit-box-tab" rows="4" cols="50" maxlength="200">
{{ text }}
</textarea>
    <button type="submit">Save</button>
</form>
</body>
</html>

textBro/main/templates/password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    <input type="text" name="enter-text-password">
    <input type="submit" value="Submit">
</form>
</body>
</html>